### ISSUE TITLE
Add options to keep sections and keys case sensitive. 

### ISSUE THREAD

**Issue by xboard** [mexili/configparser-rs#6]
I have a use case where sections have regular expressions describing file patterns, as such, preserving case sensitivity of sections values is crucial. It would be great if `configparser` had a configuration option to work in case sensitive mode.

Ini sample:
```
[([A-Z])\w+Factory.java]
    should_be_singleton = true
    abstract = false
```

Today I've no need for key values to be case sensitive but this may be useful for others.

**Comment by QEDK** [comment]
> 
> 
> I have a use case where sections have regular expressions describing file patterns, as such, preserving case sensitivity of sections values is crucial. It would be great if `configparser` had a configuration option to work in case sensitive mode.
> 
> Ini sample:
> 
> ```
> [([A-Z])\w+Factory.java]
>     should_be_singleton = true
>     abstract = false
> ```
> 
> Today I've no need for key values to be case sensitive but this may be useful for others.

I agree that there's a potential for usage. I'm thinking of a different parser and API for this, like a separate implementation with an identical outlook - or alternatively, have case-insensitive functions options and functions added. I'm currently still debating which one makes more sense:
* something like `ini::Inic` to define case-sensitive objects
* make the parser store normally by default and add case-sensitive functions 
* modify the struct to have a case-sensitive parameter and enable case-sensitive init with a custom function instead of `new()`. Then do everything under the hood.

**Comment by xboard** [comment]
The third option with a fluent idiom pattern (to keep it easy to add future configs) seems quite attractive to me. Please let me know if you think there is a way for me to help.

**Comment by QEDK** [comment]
> 
> 
> The third option with a fluent idiom pattern (to keep it easy to add future configs) seems quite attractive to me. Please let me know if you think there is a way for me to help.

Maybe you could work on the tests for the case-sensitive type? Try to have the most coverage for the least amount of code :) I'll try doing this in increments, starting with the struct.

**Comment by QEDK** [comment]
@xboard Most of the implementation is complete. See https://github.com/mexili/configparser-rs/commit/512cf1ff26df759dc255b72fc4ffa0d66f14e9d5 and let me know if things seem good.
